spring.application.name=client-api
server.port=8080

provider.api.base-url=http://provider-api:8080

resilience4j.circuitbreaker.instances.providerApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.providerApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.providerApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.providerApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.providerApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.providerApi.automaticTransitionFromOpenToHalfOpenEnabled=true

management.endpoints.web.exposure.include=health,metrics,circuitbreakers
management.endpoint.health.show-details=always

logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG